! *******************************************
       subroutine drive_PML_stress
       include 'triffy.dec'

       call sPMLTZ
       call sPMLTY
       call sPMLTX
       call sPMLBZ
       call sPMLBY
       call sPMLBX
       call sPMLTXTY
       call sPMLBXTY
       call sPMLTXBY
       call sPMLBXBY
       call sPMLTYTZ
       call sPMLBYTZ
       call sPMLTYBZ
       call sPMLBYBZ
       call sPMLTXTZ
       call sPMLBXTZ
       call sPMLTXBZ
       call sPMLBXBZ
       call sPMLTXTYTZ
       call sPMLTXTYBZ
       call sPMLTXBYTZ
       call sPMLTXBYBZ
       call sPMLBXTYTZ
       call sPMLBXTYBZ
       call sPMLBXBYTZ
       call sPMLBXBYBZ
       call PasteStressC_TX
       call PasteStressC_TY
       call PasteStressC_TZ
       call PasteStressC_BX
       call PasteStressC_BY
       call PasteStressC_BZ
       call PasteStressTX_TXTY
       call PasteStressBX_BXTY
       call PasteStressTZ_TYTZ
       call PasteStressBZ_TYBZ
       call PasteStressTX_TXBY
       call PasteStressBX_BXBY
       call PasteStressTZ_BYTZ
       call PasteStressBZ_BYBZ
       call PasteStressTX_TXTZ
       call PasteStressBX_BXTZ
       call PasteStressTY_TYTZ
       call PasteStressBY_BYTZ
       call PasteStressTX_TXBZ
       call PasteStressBX_BXBZ
       call PasteStressTY_TYBZ
       call PasteStressBY_BYBZ
       call PasteStressTY_TXTY
       call PasteStressBY_TXBY
       call PasteStressTZ_TXTZ
       call PasteStressBZ_TXBZ
       call PasteStressTY_BXTY
       call PasteStressBY_BXBY
       call PasteStressTZ_BXTZ
       call PasteStressBZ_BXBZ
       call PasteStressTXTY_TXTYTZ
       call PasteStressTXTZ_TXTYTZ
       call PasteStressTYTZ_TXTYTZ
       call PasteStressTXTY_TXTYBZ
       call PasteStressTXBZ_TXTYBZ
       call PasteStressTYBZ_TXTYBZ
       call PasteStressTXBY_TXBYTZ
       call PasteStressTXTZ_TXBYTZ
       call PasteStressBYTZ_TXBYTZ
       call PasteStressTXBY_TXBYBZ
       call PasteStressBYBZ_TXBYBZ
       call PasteStressTXBZ_TXBYBZ
       call PasteStressBXTY_BXTYTZ
       call PasteStressBXTZ_BXTYTZ
       call PasteStressTYTZ_BXTYTZ
       call PasteStressBXTY_BXTYBZ
       call PasteStressBXBZ_BXTYBZ
       call PasteStressTYBZ_BXTYBZ
       call PasteStressBXBY_BXBYTZ
       call PasteStressBXTZ_BXBYTZ
       call PasteStressBYTZ_BXBYTZ
       call PasteStressBXBY_BXBYBZ
       call PasteStressBYBZ_BXBYBZ
       call PasteStressBXBZ_BXBYBZ

      return         
      end
